### ISSUE TITLE
This unofficial API will be soon depreciated.

### ISSUE THREAD

**Issue by tetienne** [philklei/tahoma-api#16]
In a near future, all the Somfy products using the endpoint externalAPI will be migrated to use the open API. Will be nice to add a warning on the README.
Check #12 for an alternative.

**Comment by jensihnow** [comment]
Well, so far the number of supported devices is very low and there wasn't an update since July 2018. @tetienne do you have any updates from Somfy about their plans on adding more devices?

**Comment by tetienne** [comment]
Yes indeed the supported devices is very low. Sadly, I don't have any roadmap. But apparently, they want to use their own API (so the official one) for all the applications. So it means at the end we will be able to manipulate everything.

**Comment by jeroenvanderschoot** [comment]
If we add oauth login it'll be working again using this API implementation right?
Maybe that's faster than waiting for Somfy which do not respond to my questions.

**Comment by butako** [comment]
I have Velux windows and blinds. Unfortunately the official Somfy API doesn't expose the Windows. 
The Tahoma link website (https://www.tahomalink.com/enduser-mobile-web/steer-html5-client/tahoma/) still continues to show the Windows fine.

**Comment by nyroDev** [comment]
As far as I can see, the tahoma link website use the exact same API, but in another URL : `enduserAPI` instead of `externalAPI`.
And some endpoints changes too (getSetup became setup for instance, I didn't check for the others)

I did a quick test using simple curl command and it seems to work correctly.

The only security, as before, is a cookie to set on every requests.

I'm pretty sur this repo could be updated to update URLs and it will work without other works.

**Comment by jeroenvanderschoot** [comment]
> As far as I can see, the tahoma link website use the exact same API, but in another URL : `enduserAPI` instead of `externalAPI`.
> And some endpoints changes too (getSetup became setup for instance, I didn't check for the others)
> 
> I did a quick test using simple curl command and it seems to work correctly.
> 
> The only security, as before, is a cookie to set on every requests.
> 
> I'm pretty sur this repo could be updated to update URLs and it will work without other works.

I was able to change and adapt most of the requests.
The only one I'm currently struggling with is getting specific device states.
Didn't figure out the correct URL and body yet.
It used to be getStates.............

**Comment by alex7614** [comment]
Maybe Somfy support can help you ?

**Comment by alex7614** [comment]
> I was able to change and adapt most of the requests.
> The only one I'm currently struggling with is getting specific device states.
> Didn't figure out the correct URL and body yet.
> It used to be getStates.............

Maybe Somfy support can help you ?

**Comment by jeroenvanderschoot** [comment]
> > I was able to change and adapt most of the requests.
> > The only one I'm currently struggling with is getting specific device states.
> > Didn't figure out the correct URL and body yet.
> > It used to be getStates.............
> 
> Maybe Somfy support can help you ?

Think they want us to use the crippled new fancy open api.
But I just found the complete documentation of the API,
so I think I can figure it out.

**Comment by nyroDev** [comment]
Do you have a link or something for the doc of the end-user API?

**Comment by alex7614** [comment]
> > > I was able to change and adapt most of the requests.
> > > The only one I'm currently struggling with is getting specific device states.
> > > Didn't figure out the correct URL and body yet.
> > > It used to be getStates.............
> > 
> > 
> > Maybe Somfy support can help you ?
> 
> Think they want us to use the crippled new fancy open api.
> But I just found the complete documentation of the API,
> so I think I can figure it out.

Ah yes ! I think that you said is true for Somfy !

Good luck for your work 👍😀

**Comment by alex7614** [comment]
Community of openHAB fixed the Tahoma link, if it helps

https://github.com/openhab/openhab2-addons/issues/6499

https://github.com/openhab/openhab2-addons/pull/6500

https://github.com/openhab/openhab2-addons/pull/6500/commits

https://github.com/openhab/openhab2-addons/pull/6500/commits/a4df08ce0b868bd859ab6e6a16b9a7222ee326f6

**Comment by jeroenvanderschoot** [comment]
I made this API work again with new enduserAPI.
I'll fork the project and create a pull request (tomorrow)

Checked integration with Home Assistant which now fully works again.
So far for the Somfy API until it supports all devices.

**Comment by tetienne** [comment]
@jeroenvanderschoot Stupid Github notification system I miss your comment. Do you think you will be able to publish a package to pypi quickly? 
Sadly, this morning I create a PR to remove the Tahoma component from HA :S I will see if they can revert this. 

Edit: I saw your PR. Great.

**Comment by cwildt** [comment]
> I have Velux windows and blinds. Unfortunately the official Somfy API doesn't expose the Windows.
> The Tahoma link website (https://www.tahomalink.com/enduser-mobile-web/steer-html5-client/tahoma/) still continues to show the Windows fine.

You could use the Velux KLF200 to control your covers. You can access it locally, so you‘re no longer depending on somfy api‘s

**Comment by tetienne** [comment]
@cwildt The integration with the KLF200 can be done easily?

**Comment by gieljnssns** [comment]
@ everyone
Isn't it better to bring the TaHoma component back true HACS?
We don't know how long Somfy wil let us use this endpoint.
