### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by Endogen** [philklei/tahoma-api#3]
Could you please briefly describe in the README how to use this? I have a TaHoma Box and a windowing system that is based on RTS (Radio Technology Somfy). Can i already use this to control it? Or do i need Somfy Connect or anything else to start?

What i would like to do is, control the system without the need to use the Somfy App - i would like to use my own implementation for that.

**Comment by n4uti** [comment]
Philklei has done his job very well, so thanks for this :-)
I have installed his "egg" :-) on my vserver or raspberrypi and used my own python script to provide a rest api to call his api like that:

https://pastebin.com/xaqNK29S

It depends on flask, so you have to install it first.
After running the server you can use it like this:

http://127.0.0.1:5000/execute/Room%20One/up
http://127.0.0.1:5000/execute/Room%20One/my
http://127.0.0.1:5000/execute/Room%20One/down

Dont forget to use your own credentials in:

`api = TahomaApi('your@user.at', 'pw')`

And another good idea is to use an auth method like basic auth or something else. It depends on you to implement it :-)

**Comment by Endogen** [comment]
Nice! Will try it tomorrow, thanks a lot! :D

**Comment by Endogen** [comment]
@n4uti Doesn't seem to work with your implementation
`Unresolved reference 'Action'`

but i don't actually understand why. The class is defined correctly in `tahoma_api.py`

**Comment by Endogen** [comment]
Solved it. File `__init__.py` has to have:
```
from .tahoma_api import Action
```

Works great!

**Comment by n4uti** [comment]
Hm, yes its possible that i have fixed this too :)

**Comment by Endogen** [comment]
Anything else you fixed that could be helpfull for me? :)

**Comment by n4uti** [comment]
I dont think so but i will take a look after work today. Is it running and working for you, or other problems now? ;)

**Comment by Endogen** [comment]
It works fine, no issues for now. But i would be interested in cleaning up the whole project since it's basically a total mess - not the code  in `tahoma_api.py` but nearly everything else :-/
